import {
    attribute,
    autoGeneratedHashKey,
    hashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';
import { JarSettingsDto } from 'src/users/dto/jar-value.dto';
import { Preferences, UserStatus } from 'src/users/entities/user.entity';
import uuidV4 = require('uuid/v4');


@table('User')
export class UserDbo {
    @attribute()
    userId: string;

    @attribute()
    parentId?: string;

    @attribute()
    username?: string

    @attribute()
    firstName?: string

    @attribute()
    lastName?: string

    @attribute()
    emailId?: string

    @attribute()
    phoneNumber?: string

    @attribute()
    birthDate?: string

    @attribute()
    gender?: string

    @attribute()
    userStatus: UserStatus

    @attribute()
    avatar?: string

    @attribute()
    preferences: string

    @attribute()
    sharedCode: string
    @attribute()
    paymentUserId?: string;
    @attribute()
    paymentDocumentId?: string;
    @attribute()
    spendAccountId?: string;
    @attribute()
    shareAccountId?: string;
    @attribute()
    saveAccountId?: string;
    @attribute()
    achAccountId?: string;
}